---
- name: Create OpenStack config dir
  file:
    dest: /etc/openstack
    owner: root
    group: root
    state: directory

- name: Write OpenStack cloud config
  template:
    src: clouds.yaml.j2
    dest: /etc/openstack/clouds.yaml
    owner: root
    group: root
    mode: 0644
