---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a SLURM partition
- hosts: openstack

  roles:
    - role: cluster_stack
      cluster_name: "(( cluster_name }}"
      cluster_environment: [ "{{ playbook_dir }}/heat-templates/alaska-env.yaml" ]
      cluster_template: "{{ playbook_dir }}/heat-templates/alaska-cluster.yaml"
      cluster_params:
        name_prefix: "{{ cluster_name }}"
        flavor: "{{ cluster_flavor }}"
        image: "{{ cluster_image }}"
        key_name: "{{ cluster_keypair }}"
        networks:
          - network: ilab
            subnet: ilab
        num_control: 1
        num_compute: "{{ cluster_nodecount }}"
      cluster_inventory: "{{ playbook_dir }}/openhpc_cluster"
