---
heat_template_version: 2015-10-15

description: >
  Heat stack template for a stack containing one Neutron port which is on 
  the I-lab network (and does not have a floating IP)

resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: ilab
      security_groups: []
      fixed_ips:
        - subnet_id: ilab

outputs:
  OS::stack_id:
    description: The network list
    value: 
      - port: { get_resource: port }

  networks:
    description: The network list
    value: 
      - port: { get_resource: port }

  ilab_ip_address:
    description: ID of the IP assigned on the I-lab network
    value: { get_attr: [ port, fixed_ips, 0, ip_address ] }
