---
heat_template_version: 2015-10-15

description: >
  Heat stack containing a Nova instance.

parameters:
  name:
    type: string
    label: Instance name
  flavor:
    type: string
    label: Flavor name or UUID
  image:
    type: string
    label: Image name or UUID
  key_name:
    type: string
    label: SSH key pair name
  networks:
    type: json                                                                                  
    label: List of networks                                                                     
    description: >
      Each item should be a dict containing 'network', 'subnet',                                
      and 'secgroups' items. The 'secgroups' item should be a list of security
      group names or IDs.
  availability_zone:
    type: string
    label: Availability zone
    default: nova

resources:
  instance_config:
    type: Alaska::InstanceConfig

  instance_ilab:
    type: Alaska::IlabPort

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks: { get_attr: [ instance_ilab, networks ] }
      user_data: { get_resource: instance_config }
      user_data_format: SOFTWARE_CONFIG
      availability_zone: { get_param: availability_zone }

outputs:
  OS::stack_id:
    description: ID of the Nova instance
    value: { get_resource: instance }

  instance_data:
    description: ID of the Ilab IP
    value: { 'name': {get_param: name}, 'ip': {get_attr: [instance_ilab, ilab_ip_address]}, 'id': {get_resource: instance} } 
