---
heat_template_version: 2015-10-15

description: >
  Heat stack containing a group of Nova instances.

parameters:
  name_prefix:
    type: string
    label: Instance name prefix
    default: cluster
  num_compute:
    type: number
    label: Number of compute nodes
    default: 4
  num_control:
    type: number
    label: Number of control nodes
    default: 1
  flavor:
    type: string
    label: Flavor name or UUID
  image:
    type: string
    label: Image name or UUID
  networks:
    type: json
    label: List of networks
    description: >
      Each item should be a dict containing 'network', 'subnet',
      and 'secgroups' items. The 'secgroups' item should be a list of security
      group names or IDs.
  key_name:
    type: string
    label: SSH key pair name
  availability_zone:
    type: string
    label: Availability zone
    default: nova

resources:
  compute_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_compute }
      resource_def:
        type: alaska-instance.yaml
        properties:
          name: { list_join: ['-', [{ get_param: name_prefix }, 'compute', '%index%']] }
          flavor: { get_param: flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          networks: { get_param: networks }
          availability_zone: { get_param: availability_zone }

  control_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_control }
      resource_def:
        type: alaska-instance.yaml
        properties:
          name: { list_join: ['-', [{ get_param: name_prefix }, 'control', '%index%']] }
          flavor: { get_param: flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          networks: { get_param: networks }
          availability_zone: { get_param: availability_zone }

outputs:
  compute_instances:
    description: Instance data for compute nodes
    value: { get_attr: [ compute_group, instance_data ] }

  control_instances:
    description: Instance data for control nodes
    value: { get_attr: [ control_group, instance_data ] }
