---
- name: Create local user record
  user:
    state: present
    system: no
    name: "{{ item.user }}"
    uid: "{{ item.uid }}"
    comment: "{{ item.name }}"
    createhome: no
    home: "{{ homedir }}/{{ item.user }}"
    generate_ssh_key: no
    ssh_key_comment: "{{ item.name }}"
  with_items: "{{ users }}"
