---
- include: setup.yml

- hosts: orange_meta
  become: yes
  file: path=/scratch state=directory

- hosts: cluster
  remote_user: "{{ cluster_guest }}"
  become: yes
  roles:
    - role: orange_setup
    - role: orangefs
