---
- name: Generate config file
  command: pvfs2-genconfig --quiet --protocol tcp --ioservers "{{ groups['orange_data'] | join(',') }}" --metaservers "{{ groups['orange_data'] |join(',') }}" --storage /export/orangefs /etc/pvfs2.conf creates=/etc/pvfs2.conf
  become: true

- name: update storage path
  lineinfile:
    path: /etc/pvfs2.conf
    regexp: 'DataStorageSpace /export/orangefs'
    line: ' 	DataStorageSpace /export/orangefs/data'

- name: update storage path
  lineinfile:
    path: /etc/pvfs2.conf
    regexp: 'MetadataStorageSpace /export/orangefs'
    line: ' 	MetadataStorageSpace /export/orangefs/meta'

- name: probe the orangefs module
  modprobe:
    name: orangefs
    state: present

- name: format pvfs2 storage
  command: pvfs2-server -f -a "{{ inventory_hostname }}" /etc/pvfs2.conf creates=/export/orangefs/data
  when: inventory_hostname in groups['orange_data']

- name: start pvfs2 server
  systemd:
    name: orangefs
    state: started
  when: inventory_hostname in groups['orange_data']

- name: start pvfs2 client
  systemd:
    name: orangefs_client
    state: started
  when: inventory_hostname in groups['orange_client']

- name: create mountpoint scratch
  file: path=/scratch state=directory
  when: inventory_hostname in groups['orange_client']

- name: run the mount comand
  command: "mount -t pvfs2 tcp://{{ groups['orange_data'] |join('') }}:3334/orangefs /scratch"
  become: true
  when: inventory_hostname in groups['orange_client']
